---

- name: Template {{ service_unit }}
  ansible.builtin.template:
    src: service.j2
    dest: "{{ service_dir }}/{{ service_unit }}"
    owner: "{{ service_owner }}"
    group: "{{ service_group }}"
    mode: "{{ service_mode }}"
  notify: handlers.systemd.daemon_reload
  when: create_service == "true"

- name: Template {{ timer_unit }}
  ansible.builtin.template:
    src: timer.j2
    dest: "{{ timer_dir }}/{{ timer_unit }}"
    owner: "{{ timer_owner }}"
    group: "{{ timer_group }}"
    mode: "{{ timer_mode }}"
  notify: handlers.systemd.daemon_reload

- name: Enable {{ timer_unit }}
  ansible.builtin.systemd:
    name: "{{ timer_unit }}"
    enable: "{{ enable_timer }}"
